#spring.application.name=demo
server:
  port: 8080
  servlet:
    context-path: /zotri
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  multipart:
    enabled: true

spring:
  datasource:
# #    url: "jdbc:mysql://localhost:3306/zotriversedb"
#     url: "jdbc:mysql://mysql-9:3306/zotriversedb"
#     driverClassName: "com.mysql.cj.jdbc.Driver"
#     username: root
#     password: 12345
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:zotriversedb}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:admin!@#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: classpath:env.properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
